SELECT (?class as ?key) (?label AS ?value) WHERE {
  #GRAPH# 
  {
    ?class a <http://www.w3.org/2002/07/owl#Class> .
    ?class <http://www.w3.org/2000/01/rdf-schema#label> ?label .
    FILTER(lang(?label) = 'en')
  }
}