# Starts everything except the databus
version: "3.0"
name: moss-dev
services:
  lookup:
    image: lookup:dev
    container_name: moss_dev_lookup
    ports:
      - "5002:8082"
    volumes:
      - "../config/lookup-config.yml:/resources/config.yml"
      - "./index:/index"
  gstore:
    image: dbpedia/gstore:dev
    container_name: moss_dev_gstore
    environment:
      STORAGE_USER: "dba"
      STORAGE_PASS: "everyoneknows"
      STORAGE_SPARQL_ENDPOINT_URI: http://virtuoso:8890/sparql
      GSTORE_LOCALHOST_CONTEXT_FALLBACK_URL: http://172.17.0.1
      DEFAULT_JSONLD_LOCALHOST_CONTEXT: http://localhost:3000/res/context.jsonld
      DEFAULT_JSONLD_LOCALHOST_CONTEXT_LOCATION: https://databus.dbpedia.org/res/context.jsonld
    ports:
      - "5003:8080"
    volumes:
      - ./data/gstore/git:/gstore/git
      - ./data/gstore/logs:/gstore/logs
  virtuoso:
    image: "openlink/virtuoso-opensource-7:latest"
    container_name: moss_dev_virtuoso
    environment:
      DBA_PASSWORD: "everyoneknows"
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://localhost:2000"
    ports:
      - "5004:8890"
    volumes:
      - ./data/virtuoso:/database
    entrypoint: /bin/bash -c "
        echo 'grant SPARQL_LOAD_SERVICE_DATA to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SPONGE to \"SPARQL\";' >> /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SELECT_FED to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        /virtuoso-entrypoint.sh
      "
