PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?key ?value WHERE {
  ?key a ?type .
  {
    ?key rdfs:label ?value .
  }
  UNION
  {
    ?key skos:altLabel ?value .
  }
}