version: "1.0"
indexMode: INDEX_SPARQL_ENDPOINT
sparqlEndpoint: http://virtuoso:8890/sparql
indexFields:
  - fieldName: annotatedCount
    documentVariable: oeoClass
    type: numeric
    query: >
      SELECT ?oeoClass (COUNT(DISTINCT ?layer) as ?annotatedCount) WHERE {
        GRAPH ?g {
          ?layer <http://dataid.dbpedia.org/ns/moss#content> ?content .
        }
        GRAPH ?content {
          ?_ ?any ?oeoClass .
          FILTER (strstarts(str(?oeoClass), 'http://openenergy-platform.org/ontology/oeo/OEO_'))
        }
      } GROUP BY ?oeoClass