version: "1.0"
indexMode: INDEX_SPARQL_ENDPOINT
sparqlEndpoint: http://virtuoso:8890/sparql
indexFields:
  - fieldName: annotatedCount
    documentVariable: class
    type: numeric
    query: >
      SELECT ?class (COUNT(DISTINCT ?module) as ?annotatedCount) WHERE {
        GRAPH ?g {
          ?module <http://dataid.dbpedia.org/ns/moss#content> ?content .
        }
        GRAPH ?content {
          ?_ ?any ?oeoClass .
          FILTER (strstarts(str(?oeoClass), 'http://openenergy-platform.org/ontology/oeo/OEO_'))
        }
      } GROUP BY ?oeoClass
  - fieldName: class
    documentVariable: module
    type: uri
    query: >
      SELECT DISTINCT ?module ?class WHERE {
        GRAPH ?g {
          ?module <http://dataid.dbpedia.org/ns/moss#content> ?content .
          ?module <http://dataid.dbpedia.org/ns/moss#resource> ?resource .
        }
        GRAPH ?content {
          ?_ ?any ?class .
          ?class a <http://www.w3.org/2002/07/owl#Class> .
        }
        #VALUES#
      }