version: "1.0"
indexMode: INDEX_SPARQL_ENDPOINT
sparqlEndpoint: http://virtuoso:8890/sparql
indexFields:
  - fieldName: annotation
    documentVariable: layer
    type: uri
    query: >
      SELECT DISTINCT ?layer ?annotation WHERE {
        GRAPH ?g {
          ?layer <http://dataid.dbpedia.org/ns/moss#content> ?content .
        }
        GRAPH ?content {
        {
          ?_ ?_ ?annotation .
          ?annotation a <http://www.w3.org/2002/07/owl#Class> .
        }
        #VALUES#
      }
