version: "1.0"
indexMode: INDEX_SPARQL_ENDPOINT
sparqlEndpoint: http://virtuoso:8890/sparql
indexFields:
  - fieldName: annotation
    documentVariable: layer
    type: uri
    query: >
      SELECT DISTINCT ?layer ?annotation WHERE {
          GRAPH ?g {
            ?layer a <http://dataid.dbpedia.org/ns/moss#DatabusMetadataLayer> .
            ?layer <http://dataid.dbpedia.org/ns/moss#layerName> "simple" .
            ?layer <http://dataid.dbpedia.org/ns/moss#content> ?content .
            ?layer <http://dataid.dbpedia.org/ns/moss#extends> ?resource .
          }
          GRAPH ?content {
            ?resource <https://saref.etsi.org/core/isAbout> ?annotation .
          }
          #VALUES#
      }
  - fieldName: label
    documentVariable: layer
    query: >
      SELECT DISTINCT ?layer ?label WHERE {
          GRAPH ?g {
            ?layer a <http://dataid.dbpedia.org/ns/moss#DatabusMetadataLayer> .
            ?layer <http://dataid.dbpedia.org/ns/moss#layerName> "simple" .
            ?layer <http://dataid.dbpedia.org/ns/moss#content> ?content .
          }
          GRAPH ?content {
            ?resource <http://www.w3.org/2000/01/rdf-schema#label> ?label .
          }
          #VALUES#
      }
      