version: "1.0"
indexMode: INDEX_SPARQL_ENDPOINT
sparqlEndpoint: http://virtuoso:8890/sparql
indexFields:
  - fieldName: width
    documentVariable: layer
    type: uri
    query: >
      SELECT DISTINCT ?layer ?width WHERE {
        GRAPH ?g {
          ?layer <http://dataid.dbpedia.org/ns/moss#content> ?content .
          ?layer <http://dataid.dbpedia.org/ns/moss#extends> ?resource .
        }
        GRAPH ?content {
          ?resource <http://www.w3.org/2003/12/exif/ns#width> ?width .
        }
        #VALUES#
      }
  - fieldName: height
    documentVariable: layer
    type: uri
    query: >
      SELECT DISTINCT ?layer ?height WHERE {
        GRAPH ?g {
          ?layer <http://dataid.dbpedia.org/ns/moss#content> ?content .
          ?layer <http://dataid.dbpedia.org/ns/moss#extends> ?resource .
        }
        GRAPH ?content {
          ?resource <http://www.w3.org/2003/12/exif/ns#height> ?height .
        }
        #VALUES#
      }