id: image
label: Generic Image Data
description: Generic metadata for images in any format
schema: ./shapes.ttl
context: ./context.jsonld
indexerConfig: ./indexer.yaml
ontologies:
  - name: oeo
    path: oeo.ttl
    indexer: oeo-indexer.yml
