name: moss

services:
  virtuoso:
    image: openlink/virtuoso-opensource-7:latest
    restart: unless-stopped
    environment:
      DBA_PASSWORD: ${VIRTUOSO_DBA_PASSWORD}
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: http://localhost:2000
    volumes:
      - virtuoso_data:/database
    entrypoint: /bin/bash -c "
        echo 'grant SPARQL_LOAD_SERVICE_DATA to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SPONGE to \"SPARQL\";' >> /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SELECT_FED to \"SPARQL\";' >> /opt/virtuoso-opensource/initdb.d/ini.sql &&
        /virtuoso-entrypoint.sh
      "

  gstore:
    image: dbpedia/gstore:ffl
    restart: unless-stopped
    depends_on:
      - virtuoso
    environment:
      STORAGE_USER: ${GSTORE_STORAGE_USER}
      STORAGE_PASS: ${GSTORE_STORAGE_PASS}
      STORAGE_SPARQL_ENDPOINT_URI: http://virtuoso:8890/sparql
      GSTORE_LOCALHOST_CONTEXT_FALLBACK_URL: http://172.17.0.1
      DEFAULT_JSONLD_LOCALHOST_CONTEXT: http://localhost:3000/res/context.jsonld
      DEFAULT_JSONLD_LOCALHOST_CONTEXT_LOCATION: https://databus.dbpedia.org/res/context.jsonld
    volumes:
      - gstore_git:/gstore/git
      - gstore_logs:/gstore/logs

  moss-server:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - gstore
    env_file: .env
    environment:
      CONFIG_PATH: /config
      GSTORE_BASE_URL: http://gstore:8080
      STORE_SPARQL_ENDPOINT: http://virtuoso:8890/sparql
      USER_DATABASE_PATH: /data/users.db
    ports:
      - "${MOSS_SERVER_PORT}:8080"
    volumes:
      - ./config:/config
      - moss_data:/data

  moss-frontend:
    build:
      context: ../../databus-moss-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - moss-server
    env_file: .env
    environment:
      MOSS_API_SERVER_URL: http://moss-server:8080
      AUTH_OIDC_CLIENT_SCOPE: openid profile email
      AUTH_TRUST_HOST: "true"
    ports:
      - "${MOSS_FRONTEND_PORT}:3000"

volumes:
  virtuoso_data:
  gstore_git:
  gstore_logs:
  moss_data:
