loaders:
  - collectionURI: https://databus.dbpedia.org/janfo/collections/moss-ontologies
    indexer:
      configPath: ./indexers/ontology-indexer.yml
layers:
  - name: openenergy
    formatMimeType: application/ld+json
    resourceType: https://dataid.dbpedia.org/databus#Version
    templatePath: layers/openenergy/template.jsonld
    shaclPath: layers/openenergy/shapes.shacl
    indexers:
      - layers/openenergy/indexer.yml
      - indexers/annotate-count-indexer.yml
  - name: opentransport
    formatMimeType: application/ld+json
    resourceType: https://dataid.dbpedia.org/databus#Version
    templatePath: layers/opentransport/template.jsonld
    indexers:
      - layers/opentransport/indexer.yml
      - indexers/annotate-count-indexer.yml