---
indexerConfigPath: indexers
layers:
- id: layer:keyword
  formatMimeType: text/turtle
  resourceTypes: []
- id: layer:openenergy
  formatMimeType: application/ld+json
  resourceTypes: []
- id: layer:more
  formatMimeType: text/turtle
  resourceTypes: []
- id: layer:OEMetadata_2_0
  formatMimeType: application/ld+json
  resourceTypes: []
loaders:
- collectionURI: https://databus.dbpedia.org/janfo/collections/moss-ontologies
  indexers:
  - indexer:ontology
indexers:
- id: indexer:keyword
  layers: null
- id: indexer:openenergy
  layers:
  - layer:OEMetadata_2_0
- id: indexer:annotate-count
  layers:
  - layer:openenergy
  - layer:OEMetadata_2_0
- id: indexer:ontology
  layers: null
