---
indexerConfigPath: indexers
templatePath: templates
templateResourcePlaceholder: $DATABUS_RESOURCE
layers:
- id: layer:keyword
  formatMimeType: text/turtle
  resourceTypes: []
- id: layer:openenergy
  formatMimeType: application/ld+json
  resourceTypes: []
ontologies:
- dataPath: ./ontologies/oeo.ttl
  indexerConfigPath: ./ontologies/oeo-indexer.yml
indexers:
- id: indexer:keyword
  layers:
  - layer:keyword
- id: indexer:annotate-count
  layers:
  - layer:keyword
  - layer:openenergy
- id: indexer:ontology
  layers: null
- id: indexer:oemetadata
  layers:
  - layer:openenergy
