id: image
label: Generic Image Data
description: Generic metadata for images in any format

schema: shapes.ttl
indexerConfig: indexer.yaml

widget:
  type: form
  fields:
    - name: width
      label: Width
      type: integer
    - name: height
      label: Height
      type: integer
    - name: format
      label: Format
      type: select
      options: [jpg, png, tiff, bmp]